[package]
name = "annie-rlbot"
version = "0.3.0"
edition = "2024"

[dependencies]
burn = {
    version = "0.21.0",
    default-features = false,
    features = ["flex", "std"]
}
rand = { workspace = true }
rlbot-rocketsim = { git = "https://github.com/VirxEC/rlbot-rocketsim.git" }
rlgymppo-model = { path = "../rlgymppo-model" }
rlgymppo-utils = { path = "../rlgymppo-utils" }
rustc-hash = { workspace = true }
rlgymppo-rlbot = {path = "../rlgymppo-rlbot"}
