//! Nexto policy inference using a pre-generated Burn model.
//!
//! The generated backend-generic model and its BurnPack weights are committed
//! in `nexto/nexto-model.rs` and `nexto/nexto-model.bpk`. Normal builds use
//! these files directly. They are not generated by Cargo.
//!
//! The model maps `(q, kv, mask)` to `(logits, attn_weights_1,
//! attn_weights_2)`:
//!
//! - `q`: `[batch, 1, 32]` — query (self-car slice of the observation table)
//! - `kv`: `[batch, entities, 24]` — key/value table (ball, boost pads, players)
//! - `mask`: `[batch, entities]` — additive attention mask
//! - `logits`: `[batch, 90]` — one logit per discrete action
//! - `attn_weights_*`: `[batch, 1, entities]` — per-entity attention weights
//!
//! The batch and entity dims are dynamic, so one graph serves any batch of
//! players (skill tracking, transfer learning, RLBot).

use std::collections::HashMap;
use std::path::Path;

use burn::prelude::*;
use burn::tensor::cast::ToElement;
use burn_store::{BurnpackError, BurnpackStore, ModuleSnapshot};
use thiserror::Error;

use crate::obs::{KV_LEN, NextoObs, Q_LEN};

/// Pre-generated backend-generic Burn model with committed weights.
/// Its `forward(q, kv, mask)` returns
/// `(logits: Tensor<B, 2>, attn_w0: Tensor<B, 3>, attn_w1: Tensor<B, 3>)`.
/// The generated code contains constructors (e.g. `from_bytes`) this crate
/// does not use, and its generated style trips clippy (e.g. `eq_op` in reshape
/// math).
#[allow(clippy::all, dead_code)]
pub(crate) mod generated {
    include!("../nexto/nexto-model.rs");
}

/// Device-resident output of a [`NextoModel`] forward pass.
pub struct NextoOutput<B: Backend> {
    /// Per-action logits: `[batch, 90]`.
    pub logits: Tensor<B, 2>,
    /// Per-entity attention weights from the two perceiver blocks:
    /// `[batch, 1, entities]` each.
    pub attn_weights: [Tensor<B, 3>; 2],
}

/// Errors while loading or running a [`NextoModel`].
#[derive(Debug, Error)]
pub enum NextoError {
    /// The BurnPack (`.bpk`) weight file could not be read or applied.
    #[error("failed to load Nexto BurnPack weights from '{path}': {source}")]
    Burnpack {
        /// Path of the `.bpk` file that was opened.
        path: String,
        /// Underlying store error.
        source: BurnpackError,
    },
}

/// Nexto policy with dynamic player/entity counts for deterministic inference
/// on any Burn backend.
pub struct NextoModel<B: Backend> {
    net: generated::Model<B>,
    device: B::Device,
}

impl<B: Backend> NextoModel<B> {
    /// Load the default (embedded) Nexto weights onto `device`.
    ///
    /// The weights are baked into the binary at compile time as a BurnPack
    /// (`.bpk`) artifact, so no file is needed at runtime.
    pub fn new(device: &B::Device) -> Self {
        Self {
            net: generated::Model::from_embedded(device),
            device: device.clone(),
        }
    }

    /// Load Nexto weights from a BurnPack (`.bpk`) file onto `device`.
    ///
    /// The checked-in `.bpk` file is the default weight source; the extension is
    /// appended if missing.
    pub fn load(path: impl AsRef<Path>, device: &B::Device) -> Result<Self, NextoError> {
        let mut net = generated::Model::new(device);
        let mut store = BurnpackStore::from_file(path.as_ref());
        net.load_from(&mut store)
            .map_err(|source| NextoError::Burnpack {
                path: path.as_ref().display().to_string(),
                source,
            })?;
        Ok(Self {
            net,
            device: device.clone(),
        })
    }

    /// The device the model was loaded onto.
    pub fn device(&self) -> &B::Device {
        &self.device
    }

    /// Full forward pass: logits plus the two attention-weight tensors.
    pub fn forward(&self, q: Tensor<B, 3>, kv: Tensor<B, 3>, mask: Tensor<B, 2>) -> NextoOutput<B> {
        let (logits, w0, w1) = self.net.forward(q, kv, mask);
        NextoOutput {
            logits,
            attn_weights: [w0, w1],
        }
    }

    /// Per-action logits: `[batch, 90]`.
    pub fn logits(&self, q: Tensor<B, 3>, kv: Tensor<B, 3>, mask: Tensor<B, 2>) -> Tensor<B, 2> {
        self.forward(q, kv, mask).logits
    }

    /// Deterministic action index (argmax of the logits) for each row of the
    /// batch.
    pub fn actions(&self, q: Tensor<B, 3>, kv: Tensor<B, 3>, mask: Tensor<B, 2>) -> Vec<usize> {
        self.logits(q, kv, mask)
            .argmax(1)
            .into_data()
            .iter::<B::IntElem>()
            .map(|value| value.to_usize())
            .collect()
    }

    /// Deterministic action index (argmax of the logits) for a single
    /// observation. Panics if `q` has a batch size other than 1.
    pub fn action(&self, q: Tensor<B, 3>, kv: Tensor<B, 3>, mask: Tensor<B, 2>) -> usize {
        let batch = q.shape().dims::<3>()[0];
        assert_eq!(
            batch, 1,
            "Nexto single-action inference requires batch size 1, got {batch}"
        );
        self.actions(q, kv, mask)[0]
    }

    /// Run deterministic inference for observations with possibly different
    /// entity counts. Observations with the same entity count are batched.
    /// This keeps the dynamic-shape handling inside the Nexto crate.
    pub fn actions_from_observations(&self, observations: &[&NextoObs]) -> Vec<usize> {
        for (index, observation) in observations.iter().enumerate() {
            assert_eq!(
                observation.mask.len(),
                observation.kv.len(),
                "observation {index} has {} mask values for {} entities",
                observation.mask.len(),
                observation.kv.len()
            );
        }

        let mut groups: HashMap<usize, Vec<usize>> = HashMap::new();
        for (index, observation) in observations.iter().enumerate() {
            groups.entry(observation.kv.len()).or_default().push(index);
        }

        let mut actions = vec![0; observations.len()];
        for (entities, batch) in groups {
            let batch_size = batch.len();
            let mut q = Vec::with_capacity(batch_size * Q_LEN);
            let mut kv = Vec::with_capacity(batch_size * entities * KV_LEN);
            let mut mask = Vec::with_capacity(batch_size * entities);

            for &index in &batch {
                let observation = observations[index];
                q.extend_from_slice(&observation.q);
                for row in &observation.kv {
                    kv.extend_from_slice(row);
                }
                mask.extend_from_slice(&observation.mask);
            }

            let q =
                Tensor::<B, 3>::from_data(TensorData::new(q, [batch_size, 1, Q_LEN]), &self.device);
            let kv = Tensor::<B, 3>::from_data(
                TensorData::new(kv, [batch_size, entities, KV_LEN]),
                &self.device,
            );
            let mask = Tensor::<B, 2>::from_data(
                TensorData::new(mask, [batch_size, entities]),
                &self.device,
            );

            for (&index, action) in batch.iter().zip(self.actions(q, kv, mask)) {
                actions[index] = action;
            }
        }

        actions
    }
}

impl<B: Backend> Default for NextoModel<B>
where
    B::Device: Default,
{
    /// Load the default (embedded) Nexto weights onto the default device.
    fn default() -> Self {
        Self::new(&Default::default())
    }
}
